[package]
name = "rat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "huffman"
path = "src/huffman/lib.rs"

[dependencies]
bitvec = "1"
